name: Create Pre-Prod Resource

on:
  pull_request:
    types:
      - labeled

env:
  LABEL_NAME: add-test

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment-label:
    runs-on: ubuntu-latest    
    steps:
    - name: Debug output
      run: |
          echo "All labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          echo "Is label present: ${{ contains(github.event.pull_request.labels.*.name, env.LABEL_NAME) }}"
    - name: Leave a comment
      if: contains(github.event.pull_request.labels.*.name, '${{ env.LABEL_NAME }}')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const message = `
            ## ✨ Added Label: \`${{ env.LABEL_NAME }}\` ✨
            Pre-Prod Resource has been created for this PR.
          `;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

