# .github/workflows/main.yml

on:
  schedule:
  - cron: '10 8 * * *'

jobs:
  single-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: ichigo.735@gmail.com
        MIN_COMMITS_PER_DAY: 0
        MAX_COMMITS_PER_DAY: 20
        INCLUDE_WEEKENDS: false
