name: Automatic Pre-Prod Resource Cleanup

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
  pull_request:
    types:
      - unlabeled

env:
  LABEL_NAME: test-label

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:

      - name: Get PRs with test-label
        run: |
          label_name=${{ env.LABEL_NAME }}
          PRs=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/skikkh/wai-san/pulls?state=open&labels=$label_name")
          echo "$PRs" | jq -r '.[] | select(.labels[].name == $label_name) | .number' --arg label_name "$label_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Created At for Each PR
        run: |
          label_name=${{ env.LABEL_NAME }}
          PRs=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/skikkh/wai-san/pulls?state=open&labels=$label_name")
          PR_numbers=$(echo "$PRs" | jq -r '.[] | select(.labels[].name == $label_name) | .number' --arg label_name "$label_name")

          echo PR_numbers: $PR_numbers

          for PR_number in $PR_numbers; do
            created_at=$(gh api -H "Accept: application/vnd.github+json" "/repos/skikkh/wai-san/pulls/$PR_number" | jq -r '.created_at')
            echo "PR #$PR_number was created at $created_at"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if "test-label" was removed
        if: github.event.action == 'unlabeled'
        id: check-unlabel
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pr=${{ github.event.number }}
          label=$(gh api "/repos//skikkh/wai-sanissues/$pr/events" \
              --jq 'map(select(.event == "unlabeled"))[-1].label.name')

          if [[ $label == ${{ env.LABEL_NAME }} ]]; then
              echo "The ${{ env.LABEL_NAME }} label has been removed"
              echo "unlabeld_name=$label" >> $GITHUB_OUTPUT
          fi

      - name: Check if label is old enough for deletion
        id: check-label
        if: (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: |
          label_name=${{ env.LABEL_NAME }}
          label_timestamp=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/skikkh/wai-san/issues/1/comments | jq -r '.[] | select(.body | contains(${{ env.LABEL_NAME }})) | .created_at')
          echo label_timestamp: $label_timestamp
          label_timestamp_seconds=$(date -d "$label_timestamp" +"%s")
          echo label_timestamp_seconds: $label_timestamp_seconds
          current_time_seconds=$(date +"%s")
          time_difference=$((current_time_seconds - label_timestamp_seconds))
          if [ $time_difference -ge 1800 ]; then  # 1800秒（30分）以上経過したら削除
            echo "Label is old enough for deletion"
            echo "aws_resouce_deletable=true" >> $GITHUB_OUTPUT
          else
            echo "Label is not old enough for deletion"
            echo "aws_resouce_deletable=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete AWS resources
        if: (github.event.action == 'unlabeled' && steps.check-unlabel.outputs.unlabeld_name == ${{ env.LABEL_NAME }}) || steps.check-label.outputs.aws_resouce_deletable
        run: |
          echo "Delete AWS resources"
          # Stop pre-production ECS service
          # aws ecs update-service --cluster test --service test --desired-count 0

          # Stop RDS cluster
          # RDS_STATUS=$(aws rds describe-db-clusters --no-cli-pager --db-cluster-identifier ${RDS_CLUSTER_NAME} | jq -r '.DBClusters[] | .Status')
          
          # if [ "${RDS_STATUS}" == "available" ]; then
          #     echo "Stop ${RDS_CLUSTER_NAME}"
          #     aws rds stop-db-cluster --db-cluster-identifier ${RDS_CLUSTER_NAME}
          # fi
          
          # Delete Elasticache
          # aws elasticache describe-cache-clusters --no-cli-pager --cache-cluster-id ${ELASTICACHE_CLUSTER_ID} > /dev/null 2>&1
          
          # if [ $? -eq 0 ]; then
          #     echo "Delete ${ELASTICACHE_CLUSTER_ID}"
          #     aws elasticache delete-cache-cluster \
          #         --cache-cluster-id ${ELASTICACHE_CLUSTER_ID}
          # fi
          
        env:
          RDS_CLUSTER_NAME: pre-production-products
          ELASTICACHE_CLUSTER_ID: pre-production-products
